#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

function ensure_pandoc() {
    command -v pandoc >/dev/null 2>&1 || {
        echo >&2 "Could not find pandoc executable. Aborting."
        exit 1
    }
}

function generate_html_slides() {
    local -r markdown_file=$1
    local -r html_file="${markdown_file%.md}.html"

    pandoc -s \
        -t revealjs \
        -o $html_file $markdown_file \
        -V revealjs-url=https://revealjs.com \
        -V theme=solarized
}

function main() {
    ensure_pandoc

    find . -mindepth 2 -type f -name "*.md" | while read filename; do
        echo -n "${filename}... "
        generate_html_slides $filename
        echo "✓"
    done
}

main $@
